/* 
TO JEST POJEBANE I ŹLE ZROBIONE
NAWET NIE PRÓBUJ Z TEGO KORZYSTAĆ!
*/

function generate(){
	generated="<title>Tabliczka Relacyjna</title><body style='width: 802px; float:center;'><p style='width: 802px;text-align:left; font-family: Arial, Helvetica, sans-serif; text-transform:uppercase; font-size: 40px; font-weight: bold;'><span style='color:red;'>"+(document.roz.trainNo.value)+"</span><span style='float: right; font-style: italic; color:red;'>"+(document.roz.trainName.value)+"</span><center>▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬</center><span style='color:black;font-size:50px;font-family: Arial, Helvetica, sans-serif;text-transform:uppercase;font-weight: bold;'>"+(document.roz.firstStation.value)+"</span><br><br><span style='margin-left: auto;margin-right: auto;font-family: Arial, Helvetica, sans-serif; text-transform:uppercase;font-size:30px'><center>"+(document.roz.Stations.value)+"</center></span><br><br><span style='float: right; color:black;font-size:50px; font-family: Arial, Helvetica, sans-serif; text-transform:uppercase;font-weight: bold;'>"+(document.roz.lastStation.value)+"</span></p><br><br><br><br><center><a href='index.html'>Powrót</a></center></body>";
	document.write(generated)
}
function display(){
	DispWin=window.open('','NewWin','toolbar=no,status=no,width=802,height=600')
	message="<title>Tabliczka Relacyjna</title><p style='text-align:left; font-family: Arial, Helvetica, sans-serif; text-transform:uppercase; font-size: 40px; font-weight: bold;'><span style='color:red;'>"+(document.roz.trainNo.value)+"</span><span style='float: right; font-style: italic; color:red;'>"+(document.roz.trainName.value)+"</span><center>▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬</center><span style='color:black;font-size:50px;font-family: Arial, Helvetica, sans-serif;text-transform:uppercase;font-weight: bold;'>"+(document.roz.firstStation.value)+"</span><br><br><span style='margin-left: auto;margin-right: auto;font-family: Arial, Helvetica, sans-serif; text-transform:uppercase;font-size:30px'><center>"+(document.roz.Stations.value)+"</center></span><br><br><span style='float: right; color:black;font-size:50px; font-family: Arial, Helvetica, sans-serif; text-transform:uppercase;font-weight: bold;'>"+(document.roz.lastStation.value)+"</span></p>";
	DispWin.document.write(message)
}
function generujmordo() {
	document.getElementById("generated").innerHTML = "<center><div style='border-style:solid;border-width: 10px;border-color:white;width: 820px; height:auto ; float:center; background-color: white;'><p style='text-align:left; font-family: Arial, Helvetica, sans-serif; text-transform:uppercase; font-size: 40px; font-weight: bold;'><span style='color:red;'>" + (document.roz.trainNo.value) + "</span><span style='float: right; font-style: italic; color:red;'>" + (document.roz.trainName.value) + "&nbsp;&nbsp;</span><span style='color:black;font-size:15px;'><center style='color:black;'>▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬</center></span><br><span style='color:black;font-size:50px;font-family: Arial, Helvetica, sans-serif;text-transform:uppercase;font-weight: bold;float:left;'>" + (document.roz.firstStation.value) + "</span><br><br><span style='margin-left: auto;margin-right: auto;font-family: Arial, Helvetica, sans-serif; text-transform:uppercase;font-size:30px;color:black;line-height: 30px;'><center>" + (document.roz.Stations.value) + "</center></span><br><br><span style='float: right; color:black;font-size:50px; font-family: Arial, Helvetica, sans-serif; text-transform:uppercase;font-weight: bold;'>" + (document.roz.lastStation.value) +"&nbsp;&nbsp;</span><br><br></p></div></center>";
}
function generujstala() {
	document.getElementById("generated").innerHTML = "<center><div style='border-style:solid;border-width: 10px;border-color:white;width: 820px; height:500px ; float:center; background-color: white;'><p style='text-align:left; font-family: Arial, Helvetica, sans-serif; text-transform:uppercase; font-size: 40px; font-weight: bold;'><span style='color:red;'>" + (document.roz.trainNo.value) + "</span><span style='float: right; font-style: italic; color:red;'>" + (document.roz.trainName.value) + "&nbsp;&nbsp;</span><span style='color:black;font-size:15px;'><center style='color:black;'>▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬</center></span><br><span style='color:black;font-size:50px;font-family: Arial, Helvetica, sans-serif;text-transform:uppercase;font-weight: bold;float:left;'>" + (document.roz.firstStation.value) + "</span><br><br><span style='margin-left: auto;margin-right: auto;font-family: Arial, Helvetica, sans-serif; text-transform:uppercase;font-size:30px;color:black;line-height: 30px;'><center>" + (document.roz.Stations.value) + "</center></span><br><br><span style='float: right; color:black;font-size:50px; font-family: Arial, Helvetica, sans-serif; text-transform:uppercase;font-weight: bold;'>" + (document.roz.lastStation.value) +"&nbsp;&nbsp;</span><br><br></p></div></center>";
}